### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by ghost** [martinp26/motix#1]
Hello,
This is a neat font!
I'm considering using it in a website, but there isn't a license file provided, so I don't explicitly have the permission to use or distribute it publicly.

The README file says, "This is a free vector font family." Could you consider adding a license to this repository to clarify how this font may be used?
Thank you!

**Comment by martinp26** [comment]
Hi, I added a license file.  HTH

**Comment by ghost** [comment]
Thank you so much! :+1:
